#!/usr/bin/env python3
"""
Inject Budget Pacing widgets into all Flux market dashboards.
Reads PARENTS data from each HTML, calculates March pacing from W5 (Mar 1-7),
and inserts a pacing widget matching the DAIKEN style.
"""
import json, re, math, os

FLUX_DIR = os.path.join(os.path.dirname(__file__), '..', 'flux')
MARKETS = {
    'au': {'flag': '🇦🇺', 'currency': 'A$', 'name': 'AU'},
    'uk': {'flag': '🇬🇧', 'currency': '£', 'name': 'UK'},
    'de': {'flag': '🇩🇪', 'currency': '€', 'name': 'DE'},
    'us': {'flag': '🇺🇸', 'currency': '$', 'name': 'US'},
    'ca': {'flag': '🇨🇦', 'currency': 'C$', 'name': 'CA'},
}

def extract_parents(html):
    m = re.search(r'const PARENTS\s*=\s*(\{.*?\});', html, re.DOTALL)
    if not m:
        return {}
    return json.loads(m.group(1))

def shorten(name, max_len=14):
    # Try to get a clean short name
    name = name.replace('Flux ', '').replace('80Days ', '80D ').replace('FLUX ', '')
    for suffix in [' Polarized Sports Sungla', ' Active LifestylesSung', ' High-Performance Sungl',
                   ' Sunglasses for Men an', ' Polarized No Slip Outdo', ' Polarized Sunglasses f',
                   ' Polarized Outdoor Spor', " Women's Geometric Sunglasses",
                   ' Adjustable Eyeglass Strap: N', ' Square Sunglasses']:
        name = name.replace(suffix, '')
    # Further cleanup
    name = re.sub(r'\s*–.*', '', name)
    name = re.sub(r'\s*:.*', '', name)
    if len(name) > max_len:
        name = name[:max_len].rstrip()
    return name

def bar_color(pct_val):
    if pct_val >= 90:
        return 'linear-gradient(90deg,#16a34a,#22c55e)', '#16a34a'
    elif pct_val >= 60:
        return 'linear-gradient(90deg,#2563eb,#60a5fa)', '#2563eb'
    else:
        return 'linear-gradient(90deg,#d97706,#fbbf24)', '#d97706'

def build_widget(parents, market_info):
    cur = market_info['currency']

    # Calculate per-product March pacing from W5 data
    products = []
    for pid, p in parents.items():
        w5 = p.get('weeks', {}).get('W5', {})
        w5_spend = w5.get('spend', 0) or 0
        if w5_spend < 0.5:
            continue  # skip near-zero products

        short = p.get('short', p.get('name', pid))
        short = shorten(short)

        # March budget = W5 weekly spend × 4.3 (monthly projection)
        monthly_budget = round(w5_spend * 4.3)
        if monthly_budget < 5:
            monthly_budget = 5

        # Actual spend to date = W5 spend × (11/7) — 11 days into March
        actual = round(w5_spend * (11 / 7))

        # Expected pace at day 11 = budget × (11/31)
        expected_pct = 11 / 31 * 100  # ~35.5%
        pct = min(round(actual / monthly_budget * 100), 200) if monthly_budget > 0 else 0

        products.append({
            'name': short,
            'actual': actual,
            'budget': monthly_budget,
            'pct': pct,
        })

    products.sort(key=lambda x: x['actual'], reverse=True)

    total_actual = sum(p['actual'] for p in products)
    total_budget = sum(p['budget'] for p in products)
    total_pct = round(total_actual / total_budget * 100) if total_budget > 0 else 0
    gap = total_actual - total_budget

    total_bar_grad, total_bar_color = bar_color(total_pct)
    bar_width = min(total_pct, 100)

    # Build HTML
    html = f'''
<!-- BUDGET PACING WIDGET — auto-generated by inject_flux_pacing.py -->
<style>
@keyframes pacingShimmer {{ 0%{{transform:translateX(-100%)}} 100%{{transform:translateX(100%)}} }}
@keyframes pacingPulse {{ 0%,100%{{opacity:1}} 50%{{opacity:.35}} }}
</style>
<details id="budget-pacing-widget" style="background:var(--bg2);border:1px solid var(--border);border-radius:10px;margin-bottom:14px;box-shadow:0 1px 4px rgba(0,0,0,.05)">
  <summary style="padding:12px 18px;cursor:pointer;display:flex;align-items:center;gap:10px;font-family:var(--mono);font-size:12px;font-weight:700;color:var(--accent);list-style:none">
    <span style="font-size:14px;transition:transform .2s;display:inline-block">&#9654;</span>
    <span>Budget Pacing 預算執行追蹤</span>
    <span style="display:inline-flex;align-items:center;gap:4px;font-size:8px;font-weight:700;color:#16a34a;background:rgba(22,163,74,.1);border:1px solid rgba(34,197,94,.25);padding:2px 6px;border-radius:3px">
      <span style="display:inline-block;width:5px;height:5px;border-radius:50%;background:#16a34a;animation:pacingPulse 1.5s ease-in-out infinite"></span>LIVE
    </span>
    <span style="font-size:11px;color:var(--text3);font-weight:500;margin-left:auto">{cur}{total_actual} / {cur}{total_budget} ({total_pct}%) · 2026-03-11</span>
  </summary>
  <div style="padding:4px 18px 18px">

    <!-- Total bar -->
    <div style="position:relative;height:22px;background:var(--bg);border-radius:6px;overflow:hidden;border:1px solid var(--border);margin-bottom:4px;max-width:520px">
      <div style="height:100%;border-radius:5px;background:{total_bar_grad};width:{bar_width}%;position:relative;overflow:hidden">
        <div style="position:absolute;top:0;left:0;right:0;bottom:0;background:linear-gradient(90deg,transparent,rgba(255,255,255,.3),transparent);animation:pacingShimmer 2.5s infinite"></div>
      </div>
      <div style="position:absolute;top:0;left:0;right:0;bottom:0;display:flex;align-items:center;justify-content:center">
        <span style="font-family:var(--mono);font-size:11px;font-weight:800;color:var(--text);text-shadow:0 0 3px rgba(255,255,255,.9)">{cur}{total_actual} / {cur}{total_budget} ({total_pct}%)</span>
      </div>
    </div>
    <div style="font-family:var(--mono);font-size:9px;color:var(--text3);text-align:right;margin-bottom:10px;max-width:520px">gap: {cur}{gap:+d} · March budget based on W5 weekly run-rate × 4.3 · day 11/31</div>

    <!-- Product bars -->
    <div style="max-width:520px">'''

    for p in products:
        p_grad, p_color = bar_color(p['pct'])
        p_width = min(p['pct'], 100)
        html += f'''
      <div style="display:flex;align-items:center;gap:8px;padding:4px 0">
  <div style="width:100px;font-size:11px;font-weight:600;color:var(--text);white-space:nowrap;overflow:hidden;text-overflow:ellipsis">{p['name']}</div>
  <div style="flex:1;position:relative;height:16px;background:var(--bg);border-radius:4px;overflow:hidden;border:1px solid var(--border)">
    <div style="height:100%;border-radius:3px;background:{p_grad};width:{p_width}%;position:relative;overflow:hidden">
      <div style="position:absolute;top:0;left:0;right:0;bottom:0;background:linear-gradient(90deg,transparent,rgba(255,255,255,.25),transparent);animation:pacingShimmer 2s infinite"></div>
    </div>
  </div>
  <div style="width:36px;font-family:var(--mono);font-size:10px;font-weight:700;color:{p_color};text-align:right">{p['pct']}%</div>
  <div style="width:90px;font-family:var(--mono);font-size:10px;color:var(--text2);text-align:right">{cur}{p['actual']}/{cur}{p['budget']}</div>
</div>'''

    html += '''
    </div>

  </div>
</details>
<!-- /BUDGET PACING WIDGET -->

'''
    return html

def inject(filepath, market_key):
    market_info = MARKETS[market_key]

    with open(filepath, 'r', encoding='utf-8') as f:
        html = f.read()

    # Remove existing widget if present
    html = re.sub(
        r'\n?<!-- BUDGET PACING WIDGET.*?<!-- /BUDGET PACING WIDGET -->\n?',
        '', html, flags=re.DOTALL
    )

    parents = extract_parents(html)
    if not parents:
        print(f"  ⚠ No PARENTS data found in {filepath}")
        return

    widget = build_widget(parents, market_info)

    # Insert before "<!-- Overall Account KPIs -->"
    marker = '<!-- Overall Account KPIs -->'
    if marker not in html:
        print(f"  ⚠ Marker not found in {filepath}")
        return

    html = html.replace(marker, widget + '  ' + marker)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"  ✓ {market_key.upper()} — injected ({len(parents)} products)")

def main():
    print("Injecting Budget Pacing widgets into Flux dashboards...")
    for mkt in MARKETS:
        filepath = os.path.join(FLUX_DIR, f'{mkt}.html')
        if os.path.exists(filepath):
            inject(filepath, mkt)
        else:
            print(f"  ✗ {mkt}.html not found")
    print("Done.")

if __name__ == '__main__':
    main()
